/*
 * PROJECT:     LiberNT Kernel Security Support Provider Interface Driver
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     Well-known SID construction
 * COPYRIGHT:   Copyright 2026 Ahmed Arif <arif193@gmail.com>
 */

#include "ksecdd.h"

#define NDEBUG
#include <debug.h>

typedef struct _KSEC_WELL_KNOWN_SID
{
    WELL_KNOWN_SID_TYPE Type;
    SID_IDENTIFIER_AUTHORITY Authority;
    UCHAR SubAuthorityCount;
    ULONG SubAuthority[2];
} KSEC_WELL_KNOWN_SID;

static const KSEC_WELL_KNOWN_SID KsecWellKnownSids[] =
{
    { WinNullSid, SECURITY_NULL_SID_AUTHORITY, 1, { SECURITY_NULL_RID } },
    { WinWorldSid, SECURITY_WORLD_SID_AUTHORITY, 1, { SECURITY_WORLD_RID } },
    { WinLocalSid, SECURITY_LOCAL_SID_AUTHORITY, 1, { SECURITY_LOCAL_RID } },
    { WinCreatorOwnerSid, SECURITY_CREATOR_SID_AUTHORITY, 1, { SECURITY_CREATOR_OWNER_RID } },
    { WinCreatorGroupSid, SECURITY_CREATOR_SID_AUTHORITY, 1, { SECURITY_CREATOR_GROUP_RID } },
    { WinCreatorOwnerServerSid, SECURITY_CREATOR_SID_AUTHORITY, 1, { SECURITY_CREATOR_OWNER_SERVER_RID } },
    { WinCreatorGroupServerSid, SECURITY_CREATOR_SID_AUTHORITY, 1, { SECURITY_CREATOR_GROUP_SERVER_RID } },
    { WinNtAuthoritySid, SECURITY_NT_AUTHORITY, 0, { 0 } },
    { WinDialupSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_DIALUP_RID } },
    { WinNetworkSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_NETWORK_RID } },
    { WinBatchSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_BATCH_RID } },
    { WinInteractiveSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_INTERACTIVE_RID } },
    { WinServiceSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_SERVICE_RID } },
    { WinAnonymousSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_ANONYMOUS_LOGON_RID } },
    { WinProxySid, SECURITY_NT_AUTHORITY, 1, { SECURITY_PROXY_RID } },
    { WinEnterpriseControllersSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_ENTERPRISE_CONTROLLERS_RID } },
    { WinSelfSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_PRINCIPAL_SELF_RID } },
    { WinAuthenticatedUserSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_AUTHENTICATED_USER_RID } },
    { WinRestrictedCodeSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_RESTRICTED_CODE_RID } },
    { WinTerminalServerSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_TERMINAL_SERVER_RID } },
    { WinRemoteLogonIdSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_REMOTE_LOGON_RID } },
    { WinLocalSystemSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_LOCAL_SYSTEM_RID } },
    { WinLocalServiceSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_LOCAL_SERVICE_RID } },
    { WinNetworkServiceSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_NETWORK_SERVICE_RID } },
    { WinBuiltinDomainSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_BUILTIN_DOMAIN_RID } },
    { WinBuiltinAdministratorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ADMINS } },
    { WinBuiltinUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_USERS } },
    { WinBuiltinGuestsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_GUESTS } },
    { WinBuiltinPowerUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_POWER_USERS } },
    { WinBuiltinAccountOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_ACCOUNT_OPS } },
    { WinBuiltinSystemOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_SYSTEM_OPS } },
    { WinBuiltinPrintOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PRINT_OPS } },
    { WinBuiltinBackupOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_BACKUP_OPS } },
    { WinBuiltinReplicatorSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REPLICATOR } },
    { WinBuiltinPreWindows2000CompatibleAccessSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_PREW2KCOMPACCESS } },
    { WinBuiltinRemoteDesktopUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_REMOTE_DESKTOP_USERS } },
    { WinBuiltinNetworkConfigurationOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_NETWORK_CONFIGURATION_OPS } },
    { WinNTLMAuthenticationSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_NTLM_RID } },
    { WinDigestAuthenticationSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_DIGEST_RID } },
    { WinSChannelAuthenticationSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_PACKAGE_BASE_RID, SECURITY_PACKAGE_SCHANNEL_RID } },
    { WinThisOrganizationSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_THIS_ORGANIZATION_RID } },
    { WinOtherOrganizationSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_OTHER_ORGANIZATION_RID } },
    { WinBuiltinIncomingForestTrustBuildersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_INCOMING_FOREST_TRUST_BUILDERS } },
    { WinBuiltinPerfMonitoringUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_MONITORING_USERS } },
    { WinBuiltinPerfLoggingUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_LOGGING_USERS } },
    { WinBuiltinAuthorizationAccessSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_AUTHORIZATIONACCESS } },
    { WinBuiltinTerminalServerLicenseServersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_TS_LICENSE_SERVERS } },
    { WinBuiltinDCOMUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_DCOM_USERS } },
    { WinBuiltinIUsersSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_IUSERS } },
    { WinIUserSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_IUSER_RID } },
    { WinBuiltinCryptoOperatorsSid, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CRYPTO_OPERATORS } },
    { WinUntrustedLabelSid, SECURITY_MANDATORY_LABEL_AUTHORITY, 1, { SECURITY_MANDATORY_UNTRUSTED_RID } },
    { WinLowLabelSid, SECURITY_MANDATORY_LABEL_AUTHORITY, 1, { SECURITY_MANDATORY_LOW_RID } },
    { WinMediumLabelSid, SECURITY_MANDATORY_LABEL_AUTHORITY, 1, { SECURITY_MANDATORY_MEDIUM_RID } },
    { WinHighLabelSid, SECURITY_MANDATORY_LABEL_AUTHORITY, 1, { SECURITY_MANDATORY_HIGH_RID } },
    { WinSystemLabelSid, SECURITY_MANDATORY_LABEL_AUTHORITY, 1, { SECURITY_MANDATORY_SYSTEM_RID } },
    { WinWriteRestrictedCodeSid, SECURITY_NT_AUTHORITY, 1, { SECURITY_WRITE_RESTRICTED_CODE_RID } },
    { WinCreatorOwnerRightsSid, SECURITY_CREATOR_SID_AUTHORITY, 1, { SECURITY_CREATOR_OWNER_RIGHTS_RID } },
    { WinBuiltinEventLogReadersGroup, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_EVENT_LOG_READERS_GROUP } },
    { WinBuiltinCertSvcDComAccessGroup, SECURITY_NT_AUTHORITY, 2, { SECURITY_BUILTIN_DOMAIN_RID, DOMAIN_ALIAS_RID_CERTSVC_DCOM_ACCESS_GROUP } },
    { WinConsoleLogonSid, SECURITY_LOCAL_SID_AUTHORITY, 1, { SECURITY_LOCAL_LOGON_RID } },
    { WinBuiltinAnyPackageSid, SECURITY_APP_PACKAGE_AUTHORITY, 2, { SECURITY_APP_PACKAGE_BASE_RID, SECURITY_BUILTIN_PACKAGE_ANY_PACKAGE } },
};

NTSTATUS
SEC_ENTRY
SecLookupWellKnownSid(
    _In_ WELL_KNOWN_SID_TYPE SidType,
    _Out_ PSID Sid,
    _In_ ULONG SidBufferSize,
    _Inout_opt_ PULONG SidSize)
{
    const KSEC_WELL_KNOWN_SID *Entry = NULL;
    ULONG Required;
    ULONG Index;

    for (Index = 0; Index < RTL_NUMBER_OF(KsecWellKnownSids); Index++)
    {
        if (KsecWellKnownSids[Index].Type == SidType)
        {
            Entry = &KsecWellKnownSids[Index];
            break;
        }
    }
    if (Entry == NULL)
        return STATUS_INVALID_PARAMETER;

    Required = RtlLengthRequiredSid(Entry->SubAuthorityCount);
    if (SidSize != NULL)
        *SidSize = Required;
    if (Sid == NULL || SidBufferSize < Required)
        return STATUS_BUFFER_TOO_SMALL;

    RtlInitializeSid(Sid, (PSID_IDENTIFIER_AUTHORITY)&Entry->Authority, Entry->SubAuthorityCount);
    for (Index = 0; Index < Entry->SubAuthorityCount; Index++)
        *RtlSubAuthoritySid(Sid, Index) = Entry->SubAuthority[Index];
    return STATUS_SUCCESS;
}
