@ stdcall CallNtPowerInformation (long ptr long ptr long)
@ stdcall CanUserWritePwrScheme ()
@ stdcall DeletePwrScheme (long)
@ stdcall EnumPwrSchemes (ptr long)
@ stdcall GetActivePwrScheme (ptr)
@ stdcall GetCurrentPowerPolicies (ptr ptr)
@ stdcall GetPwrCapabilities (ptr)
@ stdcall GetPwrDiskSpindownRange (ptr ptr)
@ stdcall IsAdminOverrideActive (ptr)
@ stdcall IsPwrHibernateAllowed ()
@ stdcall IsPwrShutdownAllowed ()
@ stdcall IsPwrSuspendAllowed ()
@ stdcall PowerDeterminePlatformRole ()
@ stdcall PowerDeterminePlatformRoleEx(long)
@ stdcall PowerEnumerate(long ptr ptr long long ptr ptr)
@ stdcall PowerGetActiveScheme (ptr ptr)
@ stdcall PowerSetActiveScheme (ptr ptr)
@ stdcall PowerReadACValue(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadACValueIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadDCValue(ptr ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadDCValueIndex(ptr ptr ptr ptr ptr)
@ stdcall PowerReadDescription(ptr ptr ptr ptr ptr ptr)
@ stdcall PowerReadFriendlyName (ptr ptr ptr ptr ptr ptr)
@ stdcall PowerRegisterForEffectivePowerModeNotifications(long ptr ptr ptr)
@ stdcall PowerRegisterSuspendResumeNotification(long ptr ptr)
@ stdcall PowerUnregisterSuspendResumeNotification(ptr)
@ stdcall PowerSettingRegisterNotification(ptr long ptr ptr)
@ stdcall PowerSettingUnregisterNotification(ptr)
@ stdcall PowerWriteACValueIndex(ptr ptr ptr ptr long)
@ stdcall PowerWriteDCValueIndex(ptr ptr ptr ptr long)
@ stdcall PowerCreatePossibleSetting(ptr ptr ptr long)
@ stdcall PowerCreateSetting(ptr ptr ptr)
@ stdcall PowerRemovePowerSetting(ptr ptr)
@ stdcall PowerUnregisterFromEffectivePowerModeNotifications(ptr)
@ stdcall PowerWriteACDefaultIndex(ptr ptr ptr ptr long)
@ stdcall PowerWriteDCDefaultIndex(ptr ptr ptr ptr long)
@ stdcall PowerWriteDescription(ptr ptr ptr ptr ptr long)
@ stdcall PowerWriteFriendlyName(ptr ptr ptr ptr ptr long)
@ stdcall PowerWritePossibleDescription(ptr ptr ptr long ptr long)
@ stdcall PowerWritePossibleFriendlyName(ptr ptr ptr long ptr long)
@ stdcall PowerWritePossibleValue(ptr ptr ptr long long ptr long)
@ stdcall PowerWriteSettingAttributes(ptr ptr long)
@ stdcall PowerWriteValueIncrement(ptr ptr ptr long)
@ stdcall PowerWriteValueMax(ptr ptr ptr long)
@ stdcall PowerWriteValueMin(ptr ptr ptr long)
@ stdcall PowerWriteValueUnitsSpecifier(ptr ptr ptr ptr long)
@ stdcall ReadGlobalPwrPolicy (ptr)
@ stdcall ReadProcessorPwrScheme (long ptr)
@ stdcall ReadPwrScheme (long ptr)
@ stdcall SetActivePwrScheme (long ptr ptr)
@ stdcall SetSuspendState (long long long)
@ stdcall WriteGlobalPwrPolicy (ptr)
@ stdcall WriteProcessorPwrScheme (long ptr)
@ stdcall WritePwrScheme (ptr str str ptr)
@ stdcall ValidatePowerPolicies (ptr ptr)
