/* SPDX-License-Identifier: LGPL-2.1-or-later */
#pragma makedep register
[
    uuid(54e211b6-3650-4f75-8334-fa359598e1c5),
    threading(both)
]
coclass DirectManipulationManager
{
    [default] interface IDirectManipulationManager;
    interface IDirectManipulationManager2;
}

[
    uuid(79dea627-a08a-43ac-8ef5-6900b9299126),
    threading(both)
]
coclass DCompManipulationCompositor
{
    [default] interface IDirectManipulationCompositor;
    interface IDirectManipulationCompositor2;
    interface IDirectManipulationFrameInfoProvider;
}
