# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Ahmed ARIF <arif193@gmail.com>

set(ROSCONFIG_PROFILE_PACKAGES)
set(ROSCONFIG_PROFILE_CONFIGS
    "STARFIVE_JH7110_SUPPORT:BOOL=ON"
    "OARCH:STRING=rva20u64"
    "RISCV64_FAST_MISALIGNED_ACCESS:BOOL=OFF"
    "RISCV64_VECTOR:BOOL=OFF")
