# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 Ahmed ARIF <arif193@gmail.com>

set(ROSCONFIG_PROFILE_PACKAGES)
set(ROSCONFIG_PROFILE_CONFIGS
    "SPACEMIT_K1_SUPPORT:BOOL=ON"
    "RISCV64_MARCH:STRING=rva22u64"
    "RISCV64_FAST_MISALIGNED_ACCESS:BOOL=ON"
    "RISCV64_VECTOR:BOOL=ON")
