
add_subdirectory(beep)
add_subdirectory(bootvid)
add_subdirectory(condrv)
add_subdirectory(dbgcap)

if(_WINKD_)
    add_subdirectory(kdcom)
    if(ARCH STREQUAL "i386" OR ARCH STREQUAL "amd64" OR ARCH STREQUAL "arm64")
        add_subdirectory(kdgdb)
    endif()
    if(ARCH STREQUAL "i386" OR ARCH STREQUAL "amd64")
        add_subdirectory(kdvm)
    endif()
else()
    add_subdirectory(kdrosdbg)
endif()
add_subdirectory(kdstub)
add_subdirectory(kdnet)

if(NOT ARCH STREQUAL "arm")
add_subdirectory(nmidebug)
endif()
add_subdirectory(null)
add_subdirectory(werkernel)
add_subdirectory(wpprecorder)

if((ARCH STREQUAL "riscv64") AND SPACEMIT_K1_SUPPORT)
    add_subdirectory(k1xpmic)
    add_subdirectory(k1xthermal)
    add_subdirectory(k1xwdt)
endif()
