/*
 * Copyright (C) 2007 Misha Koshelev
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#define DISPID_INSTALLER_CREATERECORD 1
#define DISPID_INSTALLER_OPENPACKAGE 2
#define DISPID_INSTALLER_OPENPRODUCT 3
#define DISPID_INSTALLER_OPENDATABASE 4
#define DISPID_INSTALLER_SUMMARYINFORMATION 5
#define DISPID_INSTALLER_UILEVEL 6
#define DISPID_INSTALLER_ENABLELOG 7
#define DISPID_INSTALLER_INSTALLPRODUCT 8
#define DISPID_INSTALLER_VERSION 9
#define DISPID_INSTALLER_LASTERRORRECORD 10
#define DISPID_INSTALLER_REGISTRYVALUE 11
#define DISPID_INSTALLER_ENVIRONMENT 12
#define DISPID_INSTALLER_FILEATTRIBUTES 13
#define DISPID_INSTALLER_FILESIZE 15
#define DISPID_INSTALLER_FILEVERSION 16
#define DISPID_INSTALLER_PRODUCTSTATE 17
#define DISPID_INSTALLER_PRODUCTINFO 18
#define DISPID_INSTALLER_PRODUCTS 35
#define DISPID_INSTALLER_RELATEDPRODUCTS 40
#ifdef __REACTOS__
#define DISPID_INSTALLER_CONFIGUREPRODUCT 19
#define DISPID_INSTALLER_REINSTALLPRODUCT 20
#define DISPID_INSTALLER_COLLECTUSERINFO 21
#define DISPID_INSTALLER_APPLYPATCH 22
#define DISPID_INSTALLER_FEATUREPARENT 23
#define DISPID_INSTALLER_FEATURESTATE 24
#define DISPID_INSTALLER_USEFEATURE 25
#define DISPID_INSTALLER_FEATUREUSAGECOUNT 26
#define DISPID_INSTALLER_FEATUREUSAGEDATE 27
#define DISPID_INSTALLER_CONFIGUREFEATURE 28
#define DISPID_INSTALLER_REINSTALLFEATURE 29
#define DISPID_INSTALLER_PROVIDECOMPONENT 30
#define DISPID_INSTALLER_COMPONENTPATH 31
#define DISPID_INSTALLER_PROVIDEQUALIFIEDCOMPONENT 32
#define DISPID_INSTALLER_QUALIFIERDESCRIPTION 33
#define DISPID_INSTALLER_COMPONENTQUALIFIERS 34
#define DISPID_INSTALLER_FEATURES 36
#define DISPID_INSTALLER_COMPONENTS 37
#define DISPID_INSTALLER_COMPONENTCLIENTS 38
#define DISPID_INSTALLER_PATCHES 39
#define DISPID_INSTALLER_PATCHINFO 41
#define DISPID_INSTALLER_PATCHTRANSFORMS 42
#define DISPID_INSTALLER_ADDSOURCE 43
#define DISPID_INSTALLER_CLEARSOURCELIST 44
#define DISPID_INSTALLER_FORCESOURCELISTRESOLUTION 45
#define DISPID_INSTALLER_SHORTCUTTARGET 46
#define DISPID_INSTALLER_FILEHASH 47
#define DISPID_INSTALLER_FILESIGNATUREINFO 48
#endif

#define DISPID_RECORD_FIELDCOUNT 0
#define DISPID_RECORD_STRINGDATA 1
#define DISPID_RECORD_INTEGERDATA 2

#define DISPID_LIST__NEWENUM -4
#define DISPID_LIST_ITEM 0
#define DISPID_LIST_COUNT 1

#define DISPID_VIEW_EXECUTE 1
#define DISPID_VIEW_FETCH 2
#define DISPID_VIEW_MODIFY 3
#define DISPID_VIEW_CLOSE 4

#define DISPID_DATABASE_SUMMARYINFORMATION 2
#define DISPID_DATABASE_OPENVIEW 3

#define DISPID_SESSION_INSTALLER 1
#define DISPID_SESSION_PROPERTY 2
#define DISPID_SESSION_LANGUAGE 3
#define DISPID_SESSION_MODE 4
#define DISPID_SESSION_DATABASE 5
#define DISPID_SESSION_DOACTION 8
#define DISPID_SESSION_EVALUATECONDITION 10
#define DISPID_SESSION_MESSAGE 12
#define DISPID_SESSION_FEATURECURRENTSTATE 13
#define DISPID_SESSION_FEATUREREQUESTSTATE 14
#define DISPID_SESSION_SETINSTALLLEVEL 19

#define DISPID_SUMMARYINFO_PROPERTY 1
#define DISPID_SUMMARYINFO_PROPERTYCOUNT 2
