/*
 * PROJECT:     LiberNT SpacemiT K1 Ethernet Driver
 * LICENSE:     GPL-3.0-or-later (https://spdx.org/licenses/GPL-3.0-or-later)
 * PURPOSE:     SpacemiT K1 EMAC NDIS 6.30 miniport header
 * COPYRIGHT:   Copyright 2026 Ahmed ARIF <arif.ing@outlook.com>
 */

#pragma once

#include <ntddk.h>
#include <ndis.h>
#include <ifdef.h>
#include <ipifcons.h>

#define NDEBUG
#include <reactos/debug.h>

#ifndef ETH_LENGTH_OF_ADDRESS
#define ETH_LENGTH_OF_ADDRESS 6
#endif

#define K1XEMAC_TAG 'E1XK'
#define K1XEMAC_DRIVER_VERSION 0x0100
#define K1XEMAC_MAX_MULTICAST 32
#define K1XEMAC_MTU 1500
#define K1XEMAC_FRAME_SIZE 1514
#define K1XEMAC_FCS_SIZE 4
#define K1XEMAC_BUFFER_SIZE 1536
#define K1XEMAC_RX_RING_SIZE 1024
#define K1XEMAC_TX_RING_SIZE 256
#define K1XEMAC_RX_BUDGET 128
#define K1XEMAC_CACHE_LINE 64
#define K1XEMAC_DMA_LIMIT 0xFFFFFFFFULL
#define K1XEMAC_LINK_SPEED_10M 10000000ULL
#define K1XEMAC_LINK_SPEED_100M 100000000ULL
#define K1XEMAC_LINK_SPEED_1G 1000000000ULL
#define K1XEMAC_MAC_OPTIONS (NDIS_MAC_OPTION_TRANSFERS_NOT_PEND | \
                             NDIS_MAC_OPTION_COPY_LOOKAHEAD_DATA | \
                             NDIS_MAC_OPTION_NO_LOOPBACK)
#define K1XEMAC_SUPPORTED_FILTERS (NDIS_PACKET_TYPE_DIRECTED | \
                                   NDIS_PACKET_TYPE_MULTICAST | \
                                   NDIS_PACKET_TYPE_ALL_MULTICAST | \
                                   NDIS_PACKET_TYPE_BROADCAST | \
                                   NDIS_PACKET_TYPE_PROMISCUOUS)

#define K1X_APMU_BASE 0xD4282800ULL
#define K1X_APMU_SPAN 0x400

#define APMU_EMAC_BUS_CLOCK_ENABLE (1u << 0)
#define APMU_EMAC_RESET_RELEASE (1u << 1)
#define APMU_EMAC_RGMII (1u << 2)
#define APMU_EMAC_RMII_REFERENCE_FROM_SOC (1u << 3)
#define APMU_EMAC_RGMII_TX_CLOCK_FROM_SOC (1u << 8)
#define APMU_EMAC_AXI_SINGLE_ID (1u << 13)

#define K1X_MFPR_BASE 0xD401E000ULL
#define K1X_MFPR_SPAN 0x200
#define K1X_MFPR_OFFSET(_Gpio) (((_Gpio) + 1) * sizeof(ULONG))
#define K1X_MFPR_FUNCTION_MASK 0x7
#define K1X_MFPR_GMAC ((2u << 11) | (1u << 6) | 1u)
#define K1X_GMAC_DATA_PINS 15

#define APMU_DLINE_RX_ENABLE (1u << 0)
#define APMU_DLINE_RX_CODE_SHIFT 8
#define APMU_DLINE_RX_CODE_MASK (0xffu << 8)
#define APMU_DLINE_TX_ENABLE (1u << 16)
#define APMU_DLINE_TX_CODE_SHIFT 24
#define APMU_DLINE_TX_CODE_MASK (0xffu << 24)

#define EMAC_DMA_CONFIGURATION 0x0000
#define EMAC_DMA_CONTROL 0x0004
#define EMAC_DMA_STATUS 0x0008
#define EMAC_DMA_INTERRUPT_ENABLE 0x000c
#define EMAC_DMA_TX_AUTO_POLL 0x0010
#define EMAC_DMA_TX_POLL_DEMAND 0x0014
#define EMAC_DMA_RX_POLL_DEMAND 0x0018
#define EMAC_DMA_TX_BASE 0x001c
#define EMAC_DMA_RX_BASE 0x0020
#define EMAC_DMA_CURRENT_TX_DESCRIPTOR 0x0030
#define EMAC_DMA_CURRENT_RX_DESCRIPTOR 0x0038

#define EMAC_DMA_CONFIGURATION_RESET (1u << 0)
#define EMAC_DMA_CONFIGURATION_BURST_16 (1u << 5)
#define EMAC_DMA_CONFIGURATION_SKIP(_Words) (((ULONG)(_Words) & 0x1f) << 8)
#define EMAC_DMA_CONFIGURATION_STRICT_BURST (1u << 17)
#define EMAC_DMA_CONFIGURATION_64BIT (1u << 18)

#define EMAC_DMA_CONTROL_START_TX (1u << 0)
#define EMAC_DMA_CONTROL_START_RX (1u << 1)

#define EMAC_DMA_INT_TX_DONE (1u << 0)
#define EMAC_DMA_INT_TX_UNAVAILABLE (1u << 1)
#define EMAC_DMA_INT_TX_STOPPED (1u << 2)
#define EMAC_DMA_INT_RX_DONE (1u << 4)
#define EMAC_DMA_INT_RX_UNAVAILABLE (1u << 5)
#define EMAC_DMA_INT_RX_STOPPED (1u << 6)
#define EMAC_DMA_INT_RX_MISSED (1u << 7)
#define EMAC_DMA_INT_MAC (1u << 8)
#define EMAC_DMA_INT_ALL (EMAC_DMA_INT_TX_DONE | EMAC_DMA_INT_TX_UNAVAILABLE | \
                          EMAC_DMA_INT_TX_STOPPED | EMAC_DMA_INT_RX_DONE | \
                          EMAC_DMA_INT_RX_UNAVAILABLE | EMAC_DMA_INT_RX_STOPPED | \
                          EMAC_DMA_INT_RX_MISSED | EMAC_DMA_INT_MAC)
#define K1XEMAC_INT_MASK (EMAC_DMA_INT_TX_DONE | EMAC_DMA_INT_RX_DONE | \
                          EMAC_DMA_INT_RX_UNAVAILABLE | EMAC_DMA_INT_RX_MISSED)

#define EMAC_MAC_GLOBAL_CONTROL 0x0100
#define EMAC_MAC_TX_CONTROL 0x0104
#define EMAC_MAC_RX_CONTROL 0x0108
#define EMAC_MAC_ADDRESS_CONTROL 0x0118
#define EMAC_MAC_ADDRESS1_HIGH 0x0120
#define EMAC_MAC_ADDRESS1_MED 0x0124
#define EMAC_MAC_ADDRESS1_LOW 0x0128
#define EMAC_MAC_HASH_TABLE1 0x0150
#define EMAC_MAC_FLOW_CONTROL 0x0160
#define EMAC_MAC_MDIO_CONTROL 0x01a0
#define EMAC_MAC_MDIO_DATA 0x01a4
#define EMAC_MAC_TX_FIFO_ALMOST_FULL 0x01c0
#define EMAC_MAC_TX_START_THRESHOLD 0x01c4
#define EMAC_MAC_RX_START_THRESHOLD 0x01c8
#define EMAC_MAC_STATUS 0x01e0
#define EMAC_MAC_INTERRUPT_ENABLE 0x01e4

#define EMAC_MAC_GLOBAL_SPEED_MASK 0x3
#define EMAC_MAC_GLOBAL_SPEED_100 (1u << 0)
#define EMAC_MAC_GLOBAL_SPEED_1000 (1u << 1)
#define EMAC_MAC_GLOBAL_FULL_DUPLEX (1u << 2)
#define EMAC_MAC_GLOBAL_RESET_COUNTERS ((1u << 3) | (1u << 4))

#define EMAC_MAC_TX_ENABLE (1u << 0)
#define EMAC_MAC_TX_AUTO_RETRY (1u << 3)
#define EMAC_MAC_TX_IFG_MASK (7u << 4)

#define EMAC_MAC_RX_ENABLE (1u << 0)
#define EMAC_MAC_RX_STORE_FORWARD (1u << 3)

#define EMAC_MAC_ADDRESS1_ENABLE (1u << 0)
#define EMAC_MAC_PROMISCUOUS (1u << 8)

#define EMAC_MAC_FLOW_DECODE (1u << 0)

#define EMAC_MDIO_REGISTER_SHIFT 5
#define EMAC_MDIO_READ (1u << 10)
#define EMAC_MDIO_START (1u << 15)

#define EMAC_TX_FIFO_ALMOST_FULL_DEFAULT 0x1f8
#define EMAC_TX_STORE_FORWARD 0x5ee
#define EMAC_RX_START_DEFAULT 0xc

#define EMAC_DESC_OWN (1u << 31)
#define EMAC_RX_STATUS_FIRST (1u << 30)
#define EMAC_RX_STATUS_LAST (1u << 29)
#define EMAC_RX_STATUS_LENGTH_MASK 0x3fff
#define EMAC_RX_STATUS_RUNT (1u << 15)
#define EMAC_RX_STATUS_CRC (1u << 20)
#define EMAC_RX_STATUS_TOO_LONG (1u << 21)
#define EMAC_RX_STATUS_JABBER (1u << 22)
#define EMAC_RX_STATUS_LENGTH (1u << 23)
#define EMAC_RX_STATUS_ERRORS (EMAC_RX_STATUS_RUNT | EMAC_RX_STATUS_CRC | \
                               EMAC_RX_STATUS_TOO_LONG | EMAC_RX_STATUS_JABBER | \
                               EMAC_RX_STATUS_LENGTH)

#define EMAC_DESC_BUFFER1_MASK 0xfff
#define EMAC_DESC_END_OF_RING (1u << 26)
#define EMAC_TX_CONTROL_FIRST (1u << 29)
#define EMAC_TX_CONTROL_LAST (1u << 30)
#define EMAC_TX_CONTROL_INTERRUPT (1u << 31)

#define MII_BMCR 0
#define MII_BMSR 1
#define MII_PHYSID1 2
#define MII_PHYSID2 3
#define MII_ADVERTISE 4
#define MII_LPA 5
#define MII_CTRL1000 9
#define MII_STAT1000 10

#define BMCR_ANRESTART 0x0200
#define BMCR_ANENABLE 0x1000
#define BMSR_LSTATUS 0x0004
#define ADVERTISE_CSMA 0x0001
#define ADVERTISE_10HALF 0x0020
#define ADVERTISE_10FULL 0x0040
#define ADVERTISE_100HALF 0x0080
#define ADVERTISE_100FULL 0x0100
#define ADVERTISE_ALL (ADVERTISE_10HALF | ADVERTISE_10FULL | \
                       ADVERTISE_100HALF | ADVERTISE_100FULL)
#define ADVERTISE_1000FULL 0x0200
#define LPA_1000HALF 0x0400
#define LPA_1000FULL 0x0800

#define PHY_ID_RTL8211F 0x001cc916
#define RTL8211F_PAGE_SELECT 0x1f
#define RTL8211F_PAGE_RGMII 0xd08
#define RTL8211F_TX_DELAY_REGISTER 0x11
#define RTL8211F_TX_DELAY (1u << 8)
#define RTL8211F_RX_DELAY_REGISTER 0x15
#define RTL8211F_RX_DELAY (1u << 3)

#include <pshpack1.h>
typedef struct _K1XEMAC_DESCRIPTOR
{
    volatile ULONG Status;
    volatile ULONG Control;
    volatile ULONG Buffer1;
    volatile ULONG Buffer2;
    ULONG Skipped[12];
} K1XEMAC_DESCRIPTOR, *PK1XEMAC_DESCRIPTOR;
#include <poppack.h>

C_ASSERT(sizeof(K1XEMAC_DESCRIPTOR) == K1XEMAC_CACHE_LINE);
#define K1XEMAC_DESCRIPTOR_SKIP_WORDS (RTL_FIELD_SIZE(K1XEMAC_DESCRIPTOR, Skipped) / sizeof(ULONG))

typedef struct _K1XEMAC_RX_BUFFER
{
    PVOID VirtualAddress;
    NDIS_PHYSICAL_ADDRESS PhysicalAddress;
    PMDL Mdl;
    PNET_BUFFER_LIST NetBufferList;
    BOOLEAN Indicated;
} K1XEMAC_RX_BUFFER, *PK1XEMAC_RX_BUFFER;

typedef struct _K1XEMAC_TX_BUFFER
{
    PVOID VirtualAddress;
    NDIS_PHYSICAL_ADDRESS PhysicalAddress;
    ULONG Length;
} K1XEMAC_TX_BUFFER, *PK1XEMAC_TX_BUFFER;

typedef struct _K1XEMAC_ADAPTER
{
    NDIS_HANDLE MiniportHandle;
    PDEVICE_OBJECT PhysicalDeviceObject;

    PUCHAR RegisterBase;
    ULONG RegisterLength;
    PHYSICAL_ADDRESS RegisterPhysical;
    PUCHAR ApmuBase;
    ULONG ControlRegister;
    ULONG DelayLineRegister;

    ULONG InterruptSource;
    PKINTERRUPT InterruptObject;
    KDPC InterruptDpc;
    volatile LONG InterruptPending;

    NDIS_HANDLE RxNblPool;
    NDIS_SPIN_LOCK RxLock;
    NDIS_SPIN_LOCK TxLock;

    PK1XEMAC_DESCRIPTOR RxRing;
    NDIS_PHYSICAL_ADDRESS RxRingPhysical;
    ULONG RxRingLength;
    K1XEMAC_RX_BUFFER RxBuffers[K1XEMAC_RX_RING_SIZE];
    ULONG RxTail;

    PK1XEMAC_DESCRIPTOR TxRing;
    NDIS_PHYSICAL_ADDRESS TxRingPhysical;
    ULONG TxRingLength;
    K1XEMAC_TX_BUFFER TxBuffers[K1XEMAC_TX_RING_SIZE];
    ULONG TxHead;
    ULONG TxTail;
    ULONG TxFree;

    UCHAR PermanentMacAddress[ETH_LENGTH_OF_ADDRESS];
    UCHAR CurrentMacAddress[ETH_LENGTH_OF_ADDRESS];
    UCHAR MulticastList[K1XEMAC_MAX_MULTICAST][ETH_LENGTH_OF_ADDRESS];
    ULONG MulticastCount;
    ULONG PacketFilter;
    ULONG Lookahead;
    ULONG64 LinkSpeed;
    NDIS_MEDIA_CONNECT_STATE MediaConnectState;
    NDIS_MEDIA_DUPLEX_STATE MediaDuplexState;
    NDIS_MINIPORT_TIMER LinkTimer;
    BOOLEAN LinkTimerInitialized;
    BOOLEAN DatapathReady;
    BOOLEAN Rgmii;
    BOOLEAN PhyTxDelay;
    BOOLEAN PhyRxDelay;
    BOOLEAN ReferenceClockFromPhy;
    BOOLEAN DelayLineTuning;
    ULONG Port;
    ULONG TxPhase;
    ULONG RxPhase;
    UCHAR PhyAddress;
    ULONG PhyId;

    ULONG64 TxPackets;
    ULONG64 RxPackets;
    ULONG64 TxBytes;
    ULONG64 RxBytes;
    ULONG64 TxErrors;
    ULONG64 RxErrors;
    ULONG64 RxNoBuffer;
    ULONG InterruptCount;
} K1XEMAC_ADAPTER, *PK1XEMAC_ADAPTER;
